import { GoogleGenAI } from '@google/genai';
import { useAppStore } from '../store';

// Initialize the SDK. It automatically picks up process.env.GEMINI_API_KEY
// in the Vite environment thanks to the define in vite.config.ts.
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

async function withRetry<T>(fn: () => Promise<T>, maxRetries = 4): Promise<T> {
  let retries = 0;
  while (true) {
    try {
      return await fn();
    } catch (error: any) {
      const isRateLimit = error?.status === 429 || error?.message?.includes('429') || error?.message?.includes('quota') || error?.message?.includes('RESOURCE_EXHAUSTED');
      if (isRateLimit && retries < maxRetries) {
        retries++;
        const delay = Math.pow(2, retries) * 1000 + Math.random() * 1000;
        console.warn(`Rate limited (429). Retrying in ${Math.round(delay)}ms... (Attempt ${retries} of ${maxRetries})`);
        useAppStore.getState().setStatus(true, useAppStore.getState().progressPercent, `Rate limited. Waiting ${Math.round(delay/1000)}s before retry...`);
        await sleep(delay);
      } else {
        throw error;
      }
    }
  }
}

export async function generateText(prompt: string, systemInstruction?: string, model: string = 'gemini-3.1-pro-preview'): Promise<string> {
  try {
    const response = await withRetry(() => ai.models.generateContent({
      model: model,
      contents: prompt,
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.7,
      }
    }));
    
    // Estimate tokens (very rough estimate: 1 token ~= 4 chars)
    const estimatedTokens = Math.floor((prompt.length + (response.text?.length || 0)) / 4);

    useAppStore.getState().addLlmLog('text', { model, systemInstruction, prompt }, response.text);

    return response.text || '';
  } catch (error: any) {
    useAppStore.getState().addLlmLog('text', { model, systemInstruction, prompt }, { error: error.message || error });
    console.error("Error generating text:", error);
    throw error;
  }
}

export async function generateTextWithImage(prompt: string, imageUrl: string, systemInstruction?: string, model: string = 'gemini-3.1-flash-lite'): Promise<string> {
  try {
    const base64Str = await urlToBase64(imageUrl);
    if (!base64Str) {
      throw new Error("Failed to convert image to base64");
    }

    const match = base64Str.match(/^data:(image\/[a-zA-Z+]+);base64,(.+)$/);
    if (!match) {
      throw new Error("Invalid base64 image string");
    }

    const inlineData = {
      mimeType: match[1],
      data: match[2]
    };

    const parts = [
      { inlineData },
      { text: prompt }
    ];

    const response = await withRetry(() => ai.models.generateContent({
      model: model,
      contents: { parts },
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.7,
      }
    }));
    
    // Very rough estimate of tokens
    const estimatedTokens = Math.floor((prompt.length + (response.text?.length || 0)) / 4) + 258;

    useAppStore.getState().addLlmLog('text', { model, systemInstruction, prompt, imageUrl: imageUrl.substring(0, 50) + '...' }, response.text);

    return response.text || '';
  } catch (error: any) {
    useAppStore.getState().addLlmLog('text', { model, systemInstruction, prompt }, { error: error.message || error });
    console.error("Error generating text with image:", error);
    throw error;
  }
}

async function urlToBase64(url: string): Promise<string | null> {
  if (url.startsWith('data:')) return url;
  try {
    const res = await fetch(url);
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch (e) {
    console.error("Failed to convert URL to base64", e);
    return null;
  }
}

export async function generateImage(prompt: string, referenceImages?: string[]): Promise<string> {
  try {
    const imageModel = useAppStore.getState().imageModel || 'gemini-2.5-flash-image';

    if (imageModel.includes('imagen')) {
      const response = await withRetry<any>(() => (ai.models as any).generateImages({
        model: imageModel,
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
        }
      }));
      
      if (response.generatedImages && response.generatedImages.length > 0) {
        const base64Image = response.generatedImages[0].image.imageBytes;
        useAppStore.getState().addLlmLog('image', { model: imageModel, prompt }, "Generated Image (Base64 Hidden)");
        return `data:image/jpeg;base64,${base64Image}`;
      }
      throw new Error("No image generated by Imagen");
    } else {
      const parts: any[] = [];
      
      if (referenceImages && referenceImages.length > 0) {
        for (const img of referenceImages) {
          const base64Str = await urlToBase64(img);
          if (base64Str) {
            const match = base64Str.match(/^data:(image\/[a-zA-Z+]+);base64,(.+)$/);
            if (match) {
              parts.push({
                inlineData: {
                  mimeType: match[1],
                  data: match[2]
                }
              });
            }
          }
        }
      }
      
      parts.push({ text: prompt });

      const response = await withRetry(() => ai.models.generateContent({
        model: imageModel,
        contents: { parts },
      }));

      if (response.candidates && response.candidates.length > 0) {
        const candidate = response.candidates[0];
        
        if (candidate.content && candidate.content.parts) {
          for (const part of candidate.content.parts) {
            if (part.inlineData) {
              const base64Image = part.inlineData.data;
              useAppStore.getState().addLlmLog('image', { model: imageModel, prompt, referenceImages: referenceImages ? `${referenceImages.length} images` : 'None' }, "Generated Image (Base64 Hidden)");
              return `data:image/jpeg;base64,${base64Image}`;
            }
          }
        } else if (candidate.finishReason && candidate.finishReason !== 'STOP') {
          throw new Error(`Image generation blocked. Reason: ${candidate.finishReason}`);
        } else if (candidate.content && candidate.content.parts) {
          const textPart = candidate.content.parts.find(p => p.text);
          if (textPart && textPart.text) {
            throw new Error(`Model returned text instead of an image: "${textPart.text.substring(0, 200)}"`);
          }
        }
      }
      
      const debugInfo = response.candidates && response.candidates.length > 0 
        ? JSON.stringify(response.candidates[0]).substring(0, 300) 
        : "No candidates returned";
      throw new Error(`No image generated by Gemini. Details: ${debugInfo}`);
    }
  } catch (error: any) {
    useAppStore.getState().addLlmLog('image', { prompt, imageModel: useAppStore.getState().imageModel || 'gemini-2.5-flash-image' }, { error: error.message || error });
    console.error("Error generating image:", error);
    throw error;
  }
}

export async function generateJson<T>(prompt: string, schema: any, systemInstruction?: string, model: string = 'gemini-3.1-pro-preview'): Promise<T> {
  try {
    const response = await withRetry(() => ai.models.generateContent({
      model: model,
      contents: prompt,
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.7,
        responseMimeType: 'application/json',
        responseSchema: schema,
      }
    }));

    const estimatedTokens = Math.floor((prompt.length + (response.text?.length || 0)) / 4);

    if (!response.text) throw new Error("Empty response");
    
    useAppStore.getState().addLlmLog('text', { model, systemInstruction, schema, prompt }, response.text);
    
    return JSON.parse(response.text) as T;
  } catch (error: any) {
    useAppStore.getState().addLlmLog('text', { model, systemInstruction, schema, prompt }, { error: error.message || error });
    console.error("Error generating JSON:", error);
    throw error;
  }
}

export async function fetchAvailableModels(): Promise<{ textModels: string[], imageModels: string[] }> {
  try {
    const response = await ai.models.list();
    const textModels: string[] = [];
    const imageModels: string[] = [];

    for await (const model of response) {
      const name = model.name.replace('models/', '');
      
      // Image models: contain 'image' or 'imagen'
      if (name.includes('image') || name.includes('imagen')) {
        imageModels.push(name);
      } 
      // Text models: exclude embedding, audio, tts, veo, aqa, etc.
      else if (
        !name.includes('embedding') && 
        !name.includes('audio') && 
        !name.includes('tts') && 
        !name.includes('veo') && 
        !name.includes('aqa') &&
        (name.includes('gemini') || name.includes('gemma'))
      ) {
        textModels.push(name);
      }
    }

    // Sort to have newer versions first generally (optional, but a simple sort works)
    textModels.sort((a, b) => b.localeCompare(a));
    imageModels.sort((a, b) => b.localeCompare(a));

    return { textModels, imageModels };
  } catch (error) {
    console.error("Failed to fetch available models", error);
    // Return sensible defaults if API fails
    return { 
      textModels: ['gemini-3.1-pro-preview', 'gemini-3.1-flash-lite', 'gemini-2.5-pro', 'gemini-2.5-flash'], 
      imageModels: ['gemini-3.1-flash-image-preview', 'gemini-2.5-flash-image'] 
    };
  }
}
